CREATE TABLE NOTIFICATIONS (
   TICKET_ID     UUID         PRIMARY KEY,
   TECHNICIAN_ID UUID,
   CUSTOMER_ID   UUID         NOT NULL
   TITLE         VARCHAR(50)  NOT NULL,
   DESCRIPTION   VARCHAR(250) NOT NULL CHECK (DESCRIPTION ~ '\S'),
   PRIORITY      VARCHAR(50)  NOT NULL CHECK (PRIORITY ~ '\S'),
   STATUS        VARCHAR(50)  NOT NULL CHECK (STATUS ~ '\S'),
   CATEGORY      VARCHAR(50)  NOT NULL CHECK (CATEGORY ~ '\S'),
   CREATED_AT    TIMESTAMP    NOT NULL,
   UPDATED_AT    TIMESTAMP    NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);