CREATE TABLE NOTIFICATIONS (
   ID            UUID         PRIMARY KEY,
   TICKET_ID     UUID         NOT NULL,
   TECHNICIAN_ID UUID,
   CUSTOMER_ID   UUID         NOT NULL
   TITLE         VARCHAR(50)  NOT NULL CHECK (TITLE ~ '\S'),
   DESCRIPTION   VARCHAR(250) NOT NULL CHECK (DESCRIPTION ~ '\S'),
   MESSAGE       VARCHAR(150) NOT NULL
   PRIORITY      VARCHAR(50)  NOT NULL,
   STATUS        VARCHAR(50)  NOT NULL,
   CATEGORY      VARCHAR(50)  NOT NULL,
   CREATED_AT    TIMESTAMP    NOT NULL
);